<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tweet</name>
   <tag></tag>
   <elementGuidId>34efaf6c-d49d-46fb-b623-001e8bbd91fe</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fwww.elated.com%2Farticles%2Fjavascript-tabs%2F&amp;ref_src=twsrc%5Etfw&amp;text=JavaScript%20Tabs%20-%20Create%20Tabbed%20Web%20Pages%20Easily&amp;tw_p=tweetbutton&amp;url=https%3A%2F%2Fwww.elated.com%2Farticles%2Fjavascript-tabs%2F&amp;via=ElatedDotCom</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tweet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Windowspopup/elated.com/Page_JavaScript Tabs - Create Tabbe/iframe_twitter-widget-0</value>
   </webElementProperties>
</WebElementEntity>
